package socialmedia;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.Serializable;
/**
 * The class that contains all of the user account objects. These consist of a unique ID, a handle, a description, an arraylist of posts, comments
 * as well as endorsements 
 * 
 * @author Jack Skinner, Eleanor Forrest
 */

public class Account implements Serializable {
    // declare all the attributes
    private static int NO_OF_ACCOUNTS = 0; 
    private int id;
    private String handle; 
    private String description; 
    private int noOfEndorsements = 0;
    // We create an array list using the post, comment and endorsement classes for all of the posts linked to the account object. 
    private ArrayList<Post> posts = new ArrayList<>();

    /**
     * The first constructor for the account does not set a description and instead intitalises it to an empty string
     * 
     *  @param handle - String: the handle of the account that the user wishes to create
     * 
     * */
    public Account(String handle) {
        this.handle = handle;
        this.id = ++NO_OF_ACCOUNTS;
        this.description = ""; 
    }

    /**
     * The second constructor for the account takes the description as a parameter as well as the handle
     * 
     *  @param handle - String: the handle of the account that the user wishes to create
     *  @param description - String: the description for the account that the user wishes to create
     * 
     * */
    public Account(String handle, String description) {
        this.handle = handle; 
        this.id = ++NO_OF_ACCOUNTS;
        this.description = description;
    }
    
    /**
     * Create a Post object associated with this account, adding it to the list of posts
     * 
     * @param message - String: the message that the post should contain
     * @return id - int: the ID generated by NO_OF_POSTS which is automatically assigned and incremented
     * 
     * */
    public int makePost(String message) {
        Post p = new Post(message);
        posts.add(p); 
        return p.getId();
    }

    /**
     * Create a comment, given the ID of the original post, and a message. This comment object is of type comments
     *  
     * @param originalId - int: The ID of the original post this comment references
     * @param message - String: The message that the comment will have
     * @return id - The id of this comment, generated by NO_OF_POSTS which is automatically assigned and incremented.
     */
    public int makeComment(int originalId, String message) {
        Comment c = new Comment(message, originalId); 
        posts.add(c); 
        return c.getId();
    }
    /**
     * Create an endorsement, given the ID of the original post, the handle of the original poster, and the original posts message. 
     * The message is automatically formatted and constructed using this endorsement class
     * 
     * @param originalId - int : The ID of the original post
     * @param originalHandle - String: The handle of the original poster
     * @param orignalMessage - String: The message of the original post
     * @return id - int: the id of this endorsement, generated by NO_OF_POSTS which is automatically assigned and incremented. 
     */
    public int makeEndorsement(int originalId, String originalHandle, String orignalMessage) {
        String message = ("EP@" + originalHandle + ": " + orignalMessage);
        Endorsement e = new Endorsement(message, originalId); 
        posts.add(e);
        return e.getId();
    }
    
    /**
     * getter, returnes the private static attribute NO_OF_ACCOUTNS
     * @return NO_OF_ACCOUNTS - int: the No of accounts ever created, used to increment the ID of new accounts.
     */
    public static int getNO_OF_ACCOUNTS() {
        return NO_OF_ACCOUNTS;
    }
    
    /**
     * getter, returns the handle of the account.
     * @return handle - String: the handle of the account.
     */
    public String getHandle() {
        return handle;
    }

    /**
     * getter, returns the id of the account.
     * @return id - int: the id of the account.
     */
    public int getId() {
        return id;
    }

    /**
     * void method, used whenever an endorsement post referring to a post on this account is created.
     * increments the noOfEndorsements attribute of the account object.
     */
    public void endorsed() {
        noOfEndorsements += 1;
    }

    /**
     * void method, used whenever an endorsement post referring to a post on this account is deleted
     * decrements the noOfEndorsements attribute of the account object
     */
    public void unendorsed(){
        noOfEndorsements -= 1;
    }

    /**
     * getter, returns the description of the account.
     * @return description - String: the description of the account created.
     */
    public String getDescription() {
        return description;
    }

    /**
     * seter, updates the handle of the account object
     * @param handle - String: the new handle that will be assigned to the account.
     */ 
    public void setHandle(String handle) {
        this.handle = handle;
    }

    /**
     * setter, updates the description of the account object
     * @param description - String: the new description that will be assigned to the account.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This is used by the platform to check if an account has a post before getting it. This avoids any unwanted exceptions being raised.
     * @param id - int: the id of the post that is being looked for
     * @return boolean: weather or not this id is linked to a post in the posts arraylist.
     */
    public boolean hasPost(int id) {
        for (Post p : posts){
            if (p.getId() == id){
                return true;
            }
        }
        return false;
    }

    /** 
     * This is usually called after the check. this grabs the post if it is found to have existed in the account object's posts.
     * 
     * @param id - int: the id of the post that is being grabbed
     * @return p - Post: the post that is linked to that id.
     * @throws PostIDNotRecognisedException - Thrown when the ID does not exist in this account.
     */
    public Post getPost(int id) throws PostIDNotRecognisedException{
        for (Post p : posts){
            if (p.getId() == id){
                return p;
            }
        }
        throw new PostIDNotRecognisedException();
    }

    /**
     * This method deletes the post from the Posts arraylist, removing the posts link to the account that created it.
     * 
     * @param id - The id of the post that is being deleted from this account 
     * @throws PostIDNotRecognisedException - thrown if the id is not linked to a post in this account's post arraylist.
     */
    public void deletePost(int id) throws PostIDNotRecognisedException{
        Iterator<Post> itr = posts.iterator();
		while (itr.hasNext()) {
			Post p = (Post)itr.next();
            if (p.getId() == id){
                p.setMessage("The original content was removed from the system and is no longer available.");
                p.setPostType("DeletedPost");
                itr.remove();
                return;
            }
            
            }
        throw new PostIDNotRecognisedException();
    }
    /**
     * This method removes every post for the arraylist post. This is called before an account is deleted, to remove all of it's associated posts.
     */
    public void deleteAllPosts() {
        Iterator<Post> itr = posts.iterator();
		while (itr.hasNext()) {
			Post p = (Post)itr.next();
            p.setMessage("The original content was removed from the system and is no longer available.");
            p.setPostType("DeletedPost");
            itr.remove();            
        }
    }

    /**
     * getter - gets the size of the posts arraylist, that is to say the number of non deleted posts created by this account object.
     * @return posts.size - int: the size of the posts arraylist
     */
    public int getNoOfPosts() { 
        return posts.size();
    }

    /**
     * getter - gets the attribute numberOfEndorsements and returns this attribute.
     * @return noOfEndorsements - int: The number of Endorsements linked to this account.
     */
    public int getNoOfEndorsements() {
        return noOfEndorsements; 
    }
    /**
     * getter - loops through the posts array list. of the post is an instance of the comment class, that post is added to a new array
     * list and returned. used for showpostchildrendetails
     * @return comments - ArrayList<Comment> : an arraylist of all of the accounts comments.
     */
    public ArrayList<Comment> getComments() {
        ArrayList<Comment> comments = new ArrayList<>();
        for (Post p : posts) {
            if (p.getPostType().equals("CommentPost")) {
                Comment c = (Comment)p;
                comments.add(c);
            }
        }
        return comments;
    }

    /**
     * getter, returns the posts attribute.
     * @return posts - ArrayList<Post> : an arraylist of all the accounts linked posts.
     */
    public ArrayList<Post> getPosts(){
        return posts;
    }

    /**
     * void method, used whenever that platform is reset. Sets the counter for NO_OF_ACCOUNTS to zero, so the ids start incrementing from 1 once again.
     */
    public static void reset(){
        NO_OF_ACCOUNTS = 0;
    }
    /**
     * used to set the number of accounts when loading the platform from a file. This ensures the ids of newly created accounts are 
     * correct.
     * @param i - int: the value of NO_OF_ACCOUNTS that was saved when saveplatform was invoked.
     */
    public static void setNO_OF_ACOUNTS(Integer i) {
        NO_OF_ACCOUNTS = i;
    }

    
}
